local PalWazaIDs = {}

PalWazaIDs.SheepBall = {
   ROLY_POLY = 18,
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   IMPLODE = 33,
   ELECTRIC_BALL = 66,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.PinkCat = {
   PUNCH_FLURRY = 16,
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   WIND_CUTTER = 57,
   SEED_MACHINE_GUN = 60,
   PAL_BLAST = 10,
}

PalWazaIDs.ChickenPal = {
   CHICKEN_RUSH = 19,
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   IMPLODE = 33,
   GRASS_TORNADO = 58,
   SAND_TORNADO = 84,
   FLARE_STORM = 42,
}

PalWazaIDs.Carbunclo = {
   WIND_CUTTER = 57,
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   SEED_MACHINE_GUN = 60,
   POWER_BOMB = 12,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Kitsunebi = {
   IGNIS_BLAST = 36,
   SAND_BLAST = 87,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   IGNIS_BREATH = 37,
   SPIRIT_FLAME = 95,
   FIRE_BALL = 38,
}

PalWazaIDs.BluePlatypus = {
   AQUA_GUN = 48,
   POWER_SHOT = 11,
   HYDRO_JET = 53,
   ICE_MISSILE = 78,
   BUBBLE_BLAST = 54,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
}

PalWazaIDs.ElecCat = {
   SPARK_BLAST = 73,
   SAND_BLAST = 87,
   SHOCKWAVE = 70,
   ELECTRIC_BALL = 66,
   LIGHTNING_STREAK = 67,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.Monkey = {
   WIND_CUTTER = 57,
   SAND_BLAST = 87,
   SEED_MACHINE_GUN = 60,
   SEED_MINE = 61,
   STONE_CANNON = 85,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.FlameBambi = {
   IGNIS_BLAST = 36,
   POWER_SHOT = 11,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   FLARE_STORM = 42,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.Penguin = {
   ICE_MISSILE = 78,
   HYDRO_JET = 53,
   AQUA_GUN = 48,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   BLIZZARD_SPIKE = 81,
   HYDRO_LASER = 50,
}

PalWazaIDs.CaptainPenguin = {
   AQUA_GUN = 48,
   ICEBERG = 79,
   EMPEROR_SLIDE = 132,
   CRYST_BREATH = 106,
   AQUA_BURST = 51,
   BLIZZARD_SPIKE = 81,
   HYDRO_LASER = 50,
}

PalWazaIDs.Hedgehog = {
   SHOCKWAVE = 70,
   POWER_SHOT = 11,
   ELECTRIC_BALL = 66,
   POWER_BOMB = 12,
   LIGHTNING_STREAK = 67,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.PlantSlime = {
   SAND_BLAST = 87,
   WIND_CUTTER = 57,
   STONE_BLAST = 88,
   SEED_MACHINE_GUN = 60,
   SEED_MINE = 61,
   SAND_TORNADO = 84,
   SOLAR_BLAST = 59,
}

PalWazaIDs.CuteFox = {
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   WIND_CUTTER = 57,
   SEED_MACHINE_GUN = 60,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.WizardOwl = {
   AIR_CANNON = 22,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SAND_TORNADO = 84,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.Ganesha = {
   AQUA_GUN = 48,
   HYDRO_JET = 53,
   SAND_BLAST = 87,
   BUBBLE_BLAST = 54,
   ACID_RAIN = 55,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
}

PalWazaIDs.NegativeKoala = {
   POISON_BLAST = 94,
   SAND_BLAST = 87,
   DARK_BALL = 110,
   ICE_MISSILE = 78,
   SHADOW_BURST = 91,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.WoolFox = {
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   SPARK_BLAST = 73,
   POWER_SHOT = 11,
   SHOCKWAVE = 70,
   POWER_BOMB = 12,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.DreamDemon = {
   DARK_BALL = 110,
   POISON_BLAST = 94,
   SHADOW_BURST = 91,
   CRYST_BREATH = 106,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.Boar = {
   RECKLESS_CHARGE = 15,
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   STONE_BLAST = 88,
   POWER_BOMB = 12,
   ROCK_LANCE = 86,
   PAL_BLAST = 10,
}

PalWazaIDs.NightFox = {
   AIR_CANNON = 22,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   POWER_BOMB = 12,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.CuteMole = {
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   POWER_BOMB = 12,
   SAND_TORNADO = 84,
   ROCK_LANCE = 86,
}

PalWazaIDs.NegativeOctopus = {
   HYDRO_JET = 53,
   POISON_BLAST = 94,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   ACID_RAIN = 55,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.Bastet = {
   SAND_BLAST = 87,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SAND_TORNADO = 84,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.FlyingManta = {
   HYDRO_JET = 53,
   AQUA_GUN = 48,
   POWER_SHOT = 11,
   BUBBLE_BLAST = 54,
   SEED_MACHINE_GUN = 60,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
}

PalWazaIDs.Garm = {
   FIERCE_FANG = 13,
   SAND_BLAST = 87,
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   IGNIS_BLAST = 36,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.ColorfulBird = {
   IMPLODE = 33,
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   MEGATON_IMPLODE = 35,
   SAND_TORNADO = 84,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.FlowerRabbit = {
   WIND_CUTTER = 57,
   AIR_CANNON = 22,
   HYDRO_JET = 53,
   SEED_MACHINE_GUN = 60,
   BUBBLE_BLAST = 54,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.CowPal = {
   POWER_SHOT = 11,
   SAND_BLAST = 87,
   AIR_CANNON = 22,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.LittleBriarRose = {
   WIND_CUTTER = 57,
   SEED_MACHINE_GUN = 60,
   ICE_MISSILE = 78,
   GRASS_TORNADO = 58,
   ICEBERG = 79,
   SOLAR_BLAST = 59,
}

PalWazaIDs.SharkKid = {
   HYDRO_JET = 53,
   POWER_SHOT = 11,
   AQUA_GUN = 48,
   BUBBLE_BLAST = 54,
   ICICLE_CUTTER = 83,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
}

PalWazaIDs.WindChimes = {
   SAND_BLAST = 87,
   AIR_CANNON = 22,
   WIND_CUTTER = 57,
   POWER_SHOT = 11,
   POWER_BOMB = 12,
   SAND_TORNADO = 84,
   ROCK_LANCE = 86,
}

PalWazaIDs.GrassPanda = {
   POWER_SHOT = 11,
   SEED_MACHINE_GUN = 60,
   STONE_CANNON = 85,
   CRUSHING_PUNCH = 23,
   SEED_MINE = 61,
   SOLAR_BLAST = 59,
}

PalWazaIDs.SweetsSheep = {
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   WIND_CUTTER = 57,
   BUBBLE_BLAST = 54,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.BerryGoat = {
   WIND_CUTTER = 57,
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Alpaca = {
   AIR_CANNON = 22,
   FLUFFY_TACKLE = 25,
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   SHOCKWAVE = 70,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.Deer = {
   POWER_SHOT = 11,
   ANTLER_UPPERCUT = 9,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   POWER_BOMB = 12,
   ROCK_LANCE = 86,
   PAL_BLAST = 10,
}

PalWazaIDs.HawkBird = {
   AIR_CANNON = 22,
   TORNADO_ATTACK = 31,
   WIND_CUTTER = 57,
   POWER_BOMB = 12,
   SAND_TORNADO = 84,
   GRASS_TORNADO = 58,
   PAL_BLAST = 10,
}

PalWazaIDs.PinkRabbit = {
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   ICE_MISSILE = 78,
   BLIZZARD_SPIKE = 81,
   POWER_BOMB = 12,
   ICEBERG = 79,
   PAL_BLAST = 10,
}

PalWazaIDs.Baphomet = {
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   HELLFIRE_CLAW = 29,
   SHADOW_BURST = 91,
   FIRE_BALL = 38,
   IGNIS_RAGE = 43,
}

PalWazaIDs.CuteButterfly = {
   AIR_CANNON = 22,
   WIND_CUTTER = 57,
   POISON_FOG = 112,
   SAND_TORNADO = 84,
   SEED_MINE = 61,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.FlameBuffalo = {
   IGNIS_BLAST = 36,
   BLAZING_HORN = 47,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   IGNIS_BREATH = 37,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.LazyCatfish = {
}

PalWazaIDs.DarkCrow = {
   AIR_CANNON = 22,
   DARK_BALL = 110,
   PHANTOM_PECK = 96,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.LizardMan = {
   POISON_BLAST = 94,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   IGNIS_BREATH = 37,
   DARK_LASER = 90,
}

PalWazaIDs.Werewolf = {
   DARK_BALL = 110,
   JUMPING_CLAW = 27,
   SHADOW_BURST = 91,
   ICICLE_CUTTER = 83,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.Eagle = {
   GALE_CLAW = 32,
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   WIND_CUTTER = 57,
   SAND_TORNADO = 84,
   GRASS_TORNADO = 58,
   PAL_BLAST = 10,
}

PalWazaIDs.RobinHood = {
   WIND_CUTTER = 57,
   POWER_SHOT = 11,
   FOCUS_SHOT = 24,
   SEED_MINE = 61,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Gorilla = {
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   GROUND_POUND = 20,
   STONE_BLAST = 88,
   SEED_MACHINE_GUN = 60,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.SoldierBee = {
   AIR_CANNON = 22,
   WIND_CUTTER = 57,
   BEE_QUIET = 34,
   POISON_BLAST = 94,
   ACID_RAIN = 55,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.QueenBee = {
   AIR_CANNON = 22,
   WIND_CUTTER = 57,
   POISON_BLAST = 94,
   SPINNING_LANCE = 64,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.NaughtyCat = {
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   POWER_BOMB = 12,
   PAL_BLAST = 10,
}

PalWazaIDs.MopBaby = {
   AIR_CANNON = 22,
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   POWER_BOMB = 12,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.MopKing = {
   POWER_SHOT = 11,
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   PAL_BLAST = 10,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.WeaselDragon = {
   ICE_MISSILE = 78,
   DRAGON_CANNON = 100,
   DRAGON_BURST = 99,
   ICICLE_CUTTER = 83,
   DRACONIC_BREATH = 98,
   CRYST_BREATH = 106,
   DRAGON_METEOR = 97,
}

PalWazaIDs.Kirin = {
   SPARK_BLAST = 73,
   SHOCKWAVE = 70,
   LIGHTNING_STREAK = 67,
   LIGHTNING_STRIKE = 75,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.IceFox = {
   AIR_CANNON = 22,
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   SPIRIT_FLAME = 95,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.FireKirin = {
   SAND_BLAST = 87,
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   IGNIS_SLAM = 44,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.IceDeer = {
   AIR_CANNON = 22,
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   FREEZING_CHARGE = 122,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.ThunderDog = {
   SAND_BLAST = 87,
   SHOCKWAVE = 70,
   SPARK_BLAST = 73,
   STONE_BLAST = 88,
   ELECTRIC_BALL = 66,
   LIGHTNING_STREAK = 67,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.AmaterasuWolf = {
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   SPIRIT_FLAME = 95,
   DARING_FLAMES = 45,
   FLARE_STORM = 42,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.RaijinDaughter = {
   AIR_CANNON = 22,
   SHOCKWAVE = 70,
   ACID_RAIN = 55,
   LIGHTNING_STREAK = 67,
   LIGHTNING_STRIKE = 75,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.Mutant = {
   AIR_CANNON = 22,
   POWER_SHOT = 11,
   ICICLE_CUTTER = 83,
   PLASMA_TORNADO = 72,
   POWER_BOMB = 12,
   BLIZZARD_SPIKE = 81,
   PAL_BLAST = 10,
}

PalWazaIDs.FlowerDinosaur = {
   WIND_CUTTER = 57,
   BOTANICAL_SMASH = 17,
   DRAGON_BURST = 99,
   SEED_MINE = 61,
   DRACONIC_BREATH = 98,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Serpent = {
   HYDRO_JET = 53,
   DRAGON_CANNON = 100,
   AQUA_GUN = 48,
   BUBBLE_BLAST = 54,
   DRAGON_BURST = 99,
   DRACONIC_BREATH = 98,
   HYDRO_LASER = 50,
}

PalWazaIDs.GhostBeast = {
   IGNIS_BLAST = 36,
   DARK_BALL = 110,
   FLARE_ARROW = 39,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.DrillGame = {
   AQUA_GUN = 48,
   STONE_BLAST = 88,
   SHELL_SPIN = 89,
   STONE_CANNON = 85,
   SAND_TORNADO = 84,
   AQUA_BURST = 51,
   ROCK_LANCE = 86,
}

PalWazaIDs.CatBat = {
   AIR_CANNON = 22,
   POISON_BLAST = 94,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.PinkLizard = {
   POWER_SHOT = 11,
   POISON_BLAST = 94,
   SHADOW_BURST = 91,
   ACID_RAIN = 55,
   POWER_BOMB = 12,
   IMPLODE = 33,
   PAL_BLAST = 10,
}

PalWazaIDs.LavaGirl = {
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   SPIRIT_FLAME = 95,
   FLARE_STORM = 42,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.BirdDragon = {
   AIR_CANNON = 22,
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   IGNIS_BREATH = 37,
   NIGHTMARE_BALL = 92,
   FIRE_BALL = 38,
   DARK_LASER = 90,
}

PalWazaIDs.Ronin = {
   IGNIS_BLAST = 36,
   WIND_CUTTER = 57,
   ICICLE_CUTTER = 83,
   IAIGIRI = 133,
   IGNIS_BREATH = 37,
   LIGHTNING_STRIKE = 75,
   IGNIS_RAGE = 43,
}

PalWazaIDs.ThunderBird = {
   AIR_CANNON = 22,
   SPARK_BLAST = 73,
   SHOCKWAVE = 70,
   LIGHTNING_STREAK = 67,
   SAND_TORNADO = 84,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.RedArmorBird = {
   AIR_CANNON = 22,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   SAND_TORNADO = 84,
   FLARE_STORM = 42,
   IGNIS_BREATH = 37,
   FIRE_BALL = 38,
}

PalWazaIDs.CatMage = {
   IGNIS_BLAST = 36,
   DARK_BALL = 110,
   FLARE_ARROW = 39,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.FoxMage = {
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   SPIRIT_FLAME = 95,
   FLARE_STORM = 42,
   FIRE_BALL = 38,
   DRAGON_METEOR = 97,
}

PalWazaIDs.GrassRabbitMan = {
   WIND_CUTTER = 57,
   STONE_CANNON = 85,
   SEED_MACHINE_GUN = 60,
   STONE_BLAST = 88,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.VioletFairy = {
   POISON_FOG = 112,
   WIND_CUTTER = 57,
   POISON_BLAST = 94,
   SEED_MINE = 61,
   GRASS_TORNADO = 58,
   NIGHTMARE_BALL = 92,
   SOLAR_BLAST = 59,
}

PalWazaIDs.WhiteMoth = {
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   SPIRIT_FLAME = 95,
   AQUA_BURST = 51,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.FairyDragon = {
   DRAGON_CANNON = 100,
   DRAGON_BURST = 99,
   FLARE_ARROW = 39,
   MYSTIC_WHIRLWIND = 101,
   DRACONIC_BREATH = 98,
   PAL_BLAST = 10,
   DRAGON_METEOR = 97,
}

PalWazaIDs.Kelpie = {
   HYDRO_JET = 53,
   DRAGON_CANNON = 100,
   AQUA_GUN = 48,
   BUBBLE_BLAST = 54,
   POWER_BOMB = 12,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
}

PalWazaIDs.BlueDragon = {
   AQUA_GUN = 48,
   DRAGON_CANNON = 100,
   BUBBLE_BLAST = 54,
   DRAGON_BURST = 99,
   DRACONIC_BREATH = 98,
   HYDRO_LASER = 50,
   DRAGON_METEOR = 97,
}

PalWazaIDs.WhiteTiger = {
   POWER_SHOT = 11,
   ICE_MISSILE = 78,
   STONE_CANNON = 85,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.Manticore = {
   IGNIS_BLAST = 36,
   POWER_SHOT = 11,
   FLARE_ARROW = 39,
   IGNIS_BREATH = 37,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
   PAL_BLAST = 10,
}

PalWazaIDs.LazyDragon = {
   DRAGON_CANNON = 100,
   AQUA_GUN = 48,
   DRAGON_BURST = 99,
   BUBBLE_BLAST = 54,
   DRACONIC_BREATH = 98,
   AQUA_BURST = 51,
   DRAGON_METEOR = 97,
}

PalWazaIDs.SakuraSaurus = {
   WIND_CUTTER = 57,
   SAND_BLAST = 87,
   MUSCLE_SLAM = 129,
   SEED_MINE = 61,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.FlowerDoll = {
   WIND_CUTTER = 57,
   AQUA_GUN = 48,
   SEED_MACHINE_GUN = 60,
   BUBBLE_BLAST = 54,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.VolcanicMonster = {
   IGNIS_BLAST = 36,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   IGNIS_BREATH = 37,
   VOLCANIC_BURST = 46,
   IGNIS_RAGE = 43,
   ROCK_LANCE = 86,
}

PalWazaIDs.KingAlpaca = {
   SAND_BLAST = 87,
   POWER_SHOT = 11,
   POWER_BOMB = 12,
   KINGLY_SLAM = 26,
   ROCK_LANCE = 86,
   PAL_BLAST = 10,
}

PalWazaIDs.GrassMammoth = {
   SAND_BLAST = 87,
   SEED_MACHINE_GUN = 60,
   POWER_BOMB = 12,
   GRASS_TORNADO = 58,
   EARTH_IMPACT = 21,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Yeti = {
   ICE_MISSILE = 78,
   WIND_CUTTER = 57,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
   SOLAR_BLAST = 59,
}

PalWazaIDs.HerculesBeetle = {
   WIND_CUTTER = 57,
   SEED_MACHINE_GUN = 60,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   GIGA_HORN = 30,
   ROCK_LANCE = 86,
   SOLAR_BLAST = 59,
}

PalWazaIDs.FengyunDeeper = {
   AIR_CANNON = 22,
   AQUA_GUN = 48,
   CLOUD_TEMPEST = 28,
   ACID_RAIN = 55,
   AQUA_BURST = 51,
   BLIZZARD_SPIKE = 81,
   PAL_BLAST = 10,
}

PalWazaIDs.CatVampire = {
   POISON_BLAST = 94,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   IGNIS_RAGE = 43,
   DARK_LASER = 90,
}

PalWazaIDs.SkyDragon = {
   DRAGON_CANNON = 100,
   SPIRIT_FIRE = 40,
   ACID_RAIN = 55,
   DRACONIC_BREATH = 98,
   GRASS_TORNADO = 58,
   AQUA_BURST = 51,
   DRAGON_METEOR = 97,
}

PalWazaIDs.KingBahamut = {
   POWER_SHOT = 11,
   IGNIS_BLAST = 36,
   STONE_BLAST = 88,
   IGNIS_BREATH = 37,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
   ROCK_LANCE = 86,
}

PalWazaIDs.HadesBird = {
   SPIRIT_FIRE = 40,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   FLARE_STORM = 42,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

PalWazaIDs.BlackMetalDragon = {
   DRAGON_CANNON = 100,
   SPIRIT_FLAME = 95,
   DRAGON_BURST = 99,
   NIGHTMARE_BALL = 92,
   DRACONIC_BREATH = 98,
   DARK_LASER = 90,
   DRAGON_METEOR = 97,
}

PalWazaIDs.DarkScorpion = {
   SAND_BLAST = 87,
   POISON_BLAST = 94,
   SHADOW_BURST = 91,
   STONE_CANNON = 85,
   NIGHTMARE_BALL = 92,
   ROCK_LANCE = 86,
   DARK_LASER = 90,
}

PalWazaIDs.Anubis = {
   STONE_BLAST = 88,
   POWER_BOMB = 12,
   SAND_TORNADO = 84,
   SPINNING_ROUNDHOUSE = 6,
   FORCEFUL_CHARGE = 8,
   GROUND_SMASH = 7,
   ROCK_LANCE = 86,
}

PalWazaIDs.Umihebi = {
   AQUA_GUN = 48,
   DRAGON_CANNON = 100,
   DRACONIC_BREATH = 98,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
   DRAGON_METEOR = 97,
}

PalWazaIDs.Suzaku = {
   AIR_CANNON = 22,
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   IGNIS_BREATH = 37,
   FLARE_STORM = 42,
   FIRE_BALL = 38,
}

PalWazaIDs.ElecPanda = {
   SPARK_BLAST = 73,
   SHOCKWAVE = 70,
   LIGHTNING_CLAW = 76,
   LIGHTNING_STREAK = 67,
   LIGHTNING_STRIKE = 75,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.LilyQueen = {
   WIND_CUTTER = 57,
   SEED_MACHINE_GUN = 60,
   SEED_MINE = 61,
   AQUA_BURST = 51,
   GRASS_TORNADO = 58,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Horus = {
   IGNIS_BLAST = 36,
   FLARE_ARROW = 39,
   SPIRIT_FIRE = 40,
   IGNIS_BREATH = 37,
   PHOENIX_FLARE = 41,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.ThunderDragonMan = {
   KERAUNO = 130,
   LIGHTNING_STRIKE = 75,
   SPARK_BLAST = 73,
   DRACONIC_BREATH = 98,
   LIGHTNING_STREAK = 67,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.BlackGriffon = {
   AIR_CANNON = 22,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   DIVINE_DISASTER = 128,
   DARK_LASER = 90,
}

PalWazaIDs.SaintCentaur = {
   POWER_SHOT = 11,
   ICE_MISSILE = 78,
   ICEBERG = 79,
   POWER_BOMB = 12,
   BLIZZARD_SPIKE = 81,
   SPEAR_THRUST = 135,
   PAL_BLAST = 10,
}

PalWazaIDs.BlackCentaur = {
   SHADOW_BURST = 91,
   SPIRIT_FIRE = 40,
   SPIRIT_FLAME = 95,
   NIGHTMARE_BALL = 92,
   ROCK_LANCE = 86,
   TWIN_SPEARS = 127,
   DARK_LASER = 90,
}

PalWazaIDs.IceHorse = {
   AIR_CANNON = 22,
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYSTAL_WING = 82,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.JetDragon = {
   SPIRIT_FIRE = 40,
   DRAGON_BURST = 99,
   FLARE_STORM = 42,
   DRACONIC_BREATH = 98,
   BEAM_COMET = 118,
   FIRE_BALL = 38,
   DRAGON_METEOR = 97,
}

PalWazaIDs.Hedgehog_Ice = {
   ICE_MISSILE = 78,
   POWER_SHOT = 11,
   ICEBERG = 79,
   POWER_BOMB = 12,
   ICICLE_CUTTER = 83,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.Bastet_Ice = {
   ICE_MISSILE = 78,
   AIR_CANNON = 22,
   SAND_BLAST = 87,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.SharkKid_Fire = {
   IGNIS_BLAST = 36,
   POWER_SHOT = 11,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   LIGHTNING_STREAK = 67,
   FIRE_BALL = 38,
   IGNIS_RAGE = 43,
}

PalWazaIDs.WindChimes_Ice = {
   AIR_CANNON = 22,
   ICE_MISSILE = 78,
   POWER_SHOT = 11,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.GrassPanda_Electric = {
   SPARK_BLAST = 73,
   SHOCKWAVE = 70,
   LIGHTNING_STREAK = 67,
   BLAST_PUNCH = 145,
   LIGHTNING_STRIKE = 75,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.Deer_Ground = {
   POWER_SHOT = 11,
   ANTLER_UPPERCUT = 9,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   POWER_BOMB = 12,
   SAND_TORNADO = 84,
   ROCK_LANCE = 86,
}

PalWazaIDs.Baphomet_Dark = {
   IGNIS_BLAST = 36,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   HELLFIRE_CLAW = 29,
   SHADOW_BURST = 91,
   FIRE_BALL = 38,
   IGNIS_RAGE = 43,
}

PalWazaIDs.LizardMan_Fire = {
   IGNIS_BLAST = 36,
   POISON_BLAST = 94,
   SPIRIT_FIRE = 40,
   IGNIS_BREATH = 37,
   FLARE_STORM = 42,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
}

PalWazaIDs.RobinHood_Ground = {
   SAND_BLAST = 87,
   WIND_CUTTER = 57,
   FOCUS_SHOT = 24,
   STONE_BLAST = 88,
   SAND_TORNADO = 84,
   SOLAR_BLAST = 59,
   ROCK_LANCE = 86,
}

PalWazaIDs.FireKirin_Dark = {
   IGNIS_BLAST = 36,
   SHADOW_BURST = 91,
   IGNIS_BREATH = 37,
   SPIRIT_FLAME = 95,
   DARK_CHARGE = 141,
   IGNIS_RAGE = 43,
   DARK_LASER = 90,
}

PalWazaIDs.FlowerDinosaur_Electric = {
   SHOCKWAVE = 70,
   PLASMA_TORNADO = 72,
   BOTANICAL_SMASH = 17,
   DRACONIC_BREATH = 98,
   LIGHTNING_STRIKE = 75,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.Serpent_Ground = {
   SAND_BLAST = 87,
   DRAGON_CANNON = 100,
   STONE_BLAST = 88,
   STONE_CANNON = 85,
   SAND_TORNADO = 84,
   DRACONIC_BREATH = 98,
   ROCK_LANCE = 86,
}

PalWazaIDs.BirdDragon_Ice = {
   AIR_CANNON = 22,
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   CRYST_BREATH = 106,
   NIGHTMARE_BALL = 92,
   BLIZZARD_SPIKE = 81,
   DARK_LASER = 90,
}

PalWazaIDs.FairyDragon_Water = {
   AQUA_GUN = 48,
   DRAGON_CANNON = 100,
   DRAGON_BURST = 99,
   MYSTIC_WHIRLWIND = 101,
   ACID_RAIN = 55,
   HYDRO_LASER = 50,
   DRAGON_METEOR = 97,
}

PalWazaIDs.Kelpie_Fire = {
   IGNIS_BLAST = 36,
   DRAGON_CANNON = 100,
   SPIRIT_FIRE = 40,
   FLARE_ARROW = 39,
   DRAGON_BURST = 99,
   IGNIS_BREATH = 37,
   FIRE_BALL = 38,
}

PalWazaIDs.Manticore_Dark = {
   SHADOW_BURST = 91,
   FLARE_ARROW = 39,
   IGNIS_BREATH = 37,
   SPIRIT_FLAME = 95,
   IGNIS_RAGE = 43,
   FIRE_BALL = 38,
   DARK_LASER = 90,
}

PalWazaIDs.LazyDragon_Electric = {
   SPARK_BLAST = 73,
   DRAGON_CANNON = 100,
   SHOCKWAVE = 70,
   LIGHTNING_STREAK = 67,
   DRACONIC_BREATH = 98,
   LIGHTNING_STRIKE = 75,
   LIGHTNING_BOLT = 71,
}

PalWazaIDs.SakuraSaurus_Water = {
   AQUA_GUN = 48,
   BUBBLE_BLAST = 54,
   MUSCLE_SLAM = 129,
   SEED_MINE = 61,
   AQUA_BURST = 51,
   HYDRO_LASER = 50,
}

PalWazaIDs.VolcanicMonster_Ice = {
   ICE_MISSILE = 78,
   STONE_BLAST = 88,
   ICEBERG = 79,
   CRYST_BREATH = 106,
   FROST_BURST = 142,
   BLIZZARD_SPIKE = 81,
   ROCK_LANCE = 86,
}

PalWazaIDs.KingAlpaca_Ice = {
   ICE_MISSILE = 78,
   ICICLE_CUTTER = 83,
   ICEBERG = 79,
   KINGLY_SLAM = 26,
   CRYST_BREATH = 106,
   AQUA_BURST = 51,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.GrassMammoth_Ice = {
   STONE_CANNON = 85,
   ICICLE_CUTTER = 83,
   POWER_BOMB = 12,
   ICEBERG = 79,
   EARTH_IMPACT = 21,
   CRYST_BREATH = 106,
   BLIZZARD_SPIKE = 81,
}

PalWazaIDs.Yeti_Grass = {
   WIND_CUTTER = 57,
   AQUA_GUN = 48,
   SEED_MINE = 61,
   GRASS_TORNADO = 58,
   AQUA_BURST = 51,
   SOLAR_BLAST = 59,
}

PalWazaIDs.Umihebi_Fire = {
   IGNIS_BLAST = 36,
   DRAGON_CANNON = 100,
   FLARE_STORM = 42,
   IGNIS_BREATH = 37,
   FIRE_BALL = 38,
   DRAGON_METEOR = 97,
}

PalWazaIDs.Suzaku_Water = {
   HYDRO_JET = 53,
   ICE_MISSILE = 78,
   AQUA_GUN = 48,
   CRYST_BREATH = 106,
   AQUA_BURST = 51,
   BLIZZARD_SPIKE = 81,
   HYDRO_LASER = 50,
}

PalWazaIDs.LilyQueen_Dark = {
   DARK_BALL = 110,
   ICICLE_CUTTER = 83,
   SHADOW_BURST = 91,
   CRYST_BREATH = 106,
   NIGHTMARE_BALL = 92,
   BLIZZARD_SPIKE = 81,
   DARK_LASER = 90,
}

PalWazaIDs.IceHorse_Dark = {
   AIR_CANNON = 22,
   DARK_BALL = 110,
   SHADOW_BURST = 91,
   SPIRIT_FLAME = 95,
   CRYSTAL_WING = 82,
   NIGHTMARE_BALL = 92,
   DARK_LASER = 90,
}

return PalWazaIDs